"""Export a saved NumPy ESN as a self-contained C header."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

from .esn import EchoStateClassifier

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MODEL = REPO_ROOT / "artifacts" / "models" / "esn_model.npz"
DEFAULT_HEADER = REPO_ROOT / "firmware" / "generated" / "emberwatch_model.h"


def _c_float(value: float) -> str:
    literal = f"{float(value):.9g}"
    if "." not in literal and "e" not in literal.lower():
        literal += ".0"
    return literal + "f"


def _c_array(name: str, values: np.ndarray, columns: int = 6) -> str:
    flat = np.asarray(values, dtype=np.float32).ravel()
    rows = []
    for start in range(0, len(flat), columns):
        literals = []
        for value in flat[start : start + columns]:
            literals.append(_c_float(float(value)))
        chunk = ", ".join(literals)
        rows.append(f"    {chunk}")
    return f"static const float {name}[{len(flat)}] = {{\n" + ",\n".join(rows) + "\n};\n"


def export_model(model: EchoStateClassifier, output_path: Path) -> Path:
    config = model.config
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    text = f"""/* Generated by python -m src.export_c. Do not hand edit. */
#ifndef EMBERWATCH_MODEL_H
#define EMBERWATCH_MODEL_H

#define EW_MODEL_VERSION 1
#define EW_MODEL_INPUT_SIZE {config.input_size}
#define EW_MODEL_RESERVOIR_SIZE {config.reservoir_size}
#define EW_MODEL_OUTPUT_SIZE {config.output_size}
#define EW_MODEL_DESIGN_SIZE {1 + config.input_size + config.reservoir_size}
#define EW_MODEL_LEAK_RATE {_c_float(config.leak_rate)}
#define EW_MODEL_CLIP_NORMALIZED {_c_float(config.clip_normalized)}
#define EW_MODEL_ALERT_THRESHOLD {_c_float(model.alert_threshold)}

{_c_array("ew_model_feature_mean", model.feature_mean)}
{_c_array("ew_model_feature_std", model.feature_std)}
{_c_array("ew_model_input_weights", model.input_weights)}
{_c_array("ew_model_reservoir_weights", model.reservoir_weights)}
{_c_array("ew_model_output_weights", model.output_weights)}
#endif
"""
    output_path.write_text(text, encoding="ascii")
    return output_path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("model", nargs="?", type=Path, default=DEFAULT_MODEL)
    parser.add_argument("output", nargs="?", type=Path, default=DEFAULT_HEADER)
    args = parser.parse_args()
    model = EchoStateClassifier.load(args.model)
    output = export_model(model, args.output)
    print(f"Exported {args.model} to {output}")


if __name__ == "__main__":
    main()
