"""Export a quantized, sparse-reservoir ESN as a self-contained C header.

This is the quantized counterpart to src/export_c.py. The float exporter and
firmware/src/emberwatch_inference.c are left untouched so the float path keeps working
as a reference; this writes a separate header and pairs with
firmware/src/emberwatch_inference_q.c.

Layout written (see src/quantize.py for the quantization scheme):
    ew_q_feature_mean/std      float32, kept full precision in the normalization path
    ew_q_input_weights         row-major integer codes, one float scale per reservoir row
    ew_q_reservoir_*           CSR: values, uint8 column indices, uint16 row pointers,
                               one float scale per row
    ew_q_output_weights        row-major integer codes, one float scale per class

Usage:
    python -m src.export_c_quant                        # int8 sparse, default paths
    python -m src.export_c_quant --bits 16
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

from .esn import EchoStateClassifier
from .quantize import QuantSpec, QuantizedESN

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MODEL = REPO_ROOT / "artifacts" / "models" / "esn_model.npz"
DEFAULT_HEADER = REPO_ROOT / "firmware" / "generated" / "emberwatch_model_q.h"


def _c_float(value: float) -> str:
    literal = f"{float(value):.9g}"
    if "." not in literal and "e" not in literal.lower():
        literal += ".0"
    return literal + "f"


def _float_array(name: str, values: np.ndarray, columns: int = 6) -> str:
    flat = np.asarray(values, dtype=np.float32).ravel()
    rows = [
        "    " + ", ".join(_c_float(float(v)) for v in flat[start : start + columns])
        for start in range(0, len(flat), columns)
    ]
    return f"static const float {name}[{len(flat)}] = {{\n" + ",\n".join(rows) + "\n};\n"


def _int_array(name: str, values: np.ndarray, c_type: str, columns: int = 16) -> str:
    flat = np.asarray(values).ravel()
    rows = [
        "    " + ", ".join(str(int(v)) for v in flat[start : start + columns])
        for start in range(0, len(flat), columns)
    ]
    return f"static const {c_type} {name}[{len(flat)}] = {{\n" + ",\n".join(rows) + "\n};\n"


def export_quantized(model: EchoStateClassifier, spec: QuantSpec, output_path: Path) -> tuple[Path, dict]:
    if not spec.sparse_reservoir:
        raise ValueError("the C runtime expects a CSR reservoir; use sparse_reservoir=True")
    quantized = QuantizedESN(model, spec)
    config = model.config
    packed = quantized.reservoir_packed
    weight_type = "int8_t" if spec.bits == 8 else "int16_t"
    sizes = quantized.size_bytes()

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    text = f"""/* Generated by python -m src.export_c_quant. Do not hand edit. */
#ifndef EMBERWATCH_MODEL_Q_H
#define EMBERWATCH_MODEL_Q_H

#include <stdint.h>

#define EW_Q_VERSION 1
#define EW_Q_BITS {spec.bits}
#define EW_Q_INPUT_SIZE {config.input_size}
#define EW_Q_RESERVOIR_SIZE {config.reservoir_size}
#define EW_Q_OUTPUT_SIZE {config.output_size}
#define EW_Q_DESIGN_SIZE {1 + config.input_size + config.reservoir_size}
#define EW_Q_RESERVOIR_NNZ {int(packed["values"].size)}
#define EW_Q_LEAK_RATE {_c_float(config.leak_rate)}
#define EW_Q_CLIP_NORMALIZED {_c_float(config.clip_normalized)}
#define EW_Q_ALERT_THRESHOLD {_c_float(model.alert_threshold)}
#define EW_Q_CONSTANT_BYTES {sizes["total"]}

typedef {weight_type} ew_q_weight_t;

{_float_array("ew_q_feature_mean", quantized.feature_mean)}
{_float_array("ew_q_feature_std", quantized.feature_std)}
{_int_array("ew_q_input_weights", quantized.input_codes, weight_type)}
{_float_array("ew_q_input_scales", quantized.input_scales)}
{_int_array("ew_q_reservoir_values", packed["values"], weight_type)}
{_int_array("ew_q_reservoir_indices", packed["indices"], "uint8_t")}
{_int_array("ew_q_reservoir_row_ptr", packed["row_ptr"], "uint16_t")}
{_float_array("ew_q_reservoir_scales", packed["scales"])}
{_int_array("ew_q_output_weights", quantized.output_codes, weight_type)}
{_float_array("ew_q_output_scales", quantized.output_scales)}
#endif
"""
    output_path.write_text(text, encoding="ascii")
    return output_path, sizes


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL)
    parser.add_argument("--output", type=Path, default=DEFAULT_HEADER)
    parser.add_argument("--bits", type=int, default=8, choices=(8, 16))
    args = parser.parse_args()

    model = EchoStateClassifier.load(args.model)
    spec = QuantSpec(bits=args.bits, sparse_reservoir=True)
    output, sizes = export_quantized(model, spec, args.output)
    print(f"Exported {args.model} to {output} ({spec.name})")
    print(f"  constant bytes: {sizes['total']} (reservoir non-zeros: {sizes['reservoir_nonzero']})")


if __name__ == "__main__":
    main()
